markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : zenxin
production_url : https://www.zenxin.love
description: "我们奔跑在这条路的中间，我们哭泣着在着条路的两端。"
disqus_shortname: 
analytics: 
gauges: 
author :
  name : 吴望言
  github : 4ga1n
  twitter : 
  email: 
baseurl: /
